version: '3.6'
services:
  database:
    image: postgres
    ports:
    - "5432:5432"    
    restart: always
    environment:
      - POSTGRES_PASSWORD=robotsandpencils
  rest:
    image: node:12
    volumes:
    - ./:/usr/src/app
    ports:
    - "3001:3000"
    depends_on:
    - "database"
    restart: always
    command: bash -c "npm install && npm run start"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - PGHOST=postgres
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=robotsandpencils
      - PORT=3000
