version: '3.6'
services:
  database:
    image: postgres
    volumes:
    - ./lib/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - "5432:5432"    
    restart: always
    environment:
      - POSTGRES_PASSWORD=your_password
  rest:
    image: node:13.5.0
    volumes:
    - ./:/usr/src/app
    ports:
    - "3001:3001"
    depends_on:
    - "database"
    restart: always
    command: bash -c "npm install && npm run start"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - PGHOST=database
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=your_password
      - PGPORT=5432
      - PORT=3001
