
-- Drop table

-- DROP TABLE public.flights;

CREATE TABLE public.flights (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	launch_date timestamp NOT NULL,
	details text NULL,
	rocket_id int4 NULL,
	CONSTRAINT flights_pk PRIMARY KEY (id)
);

ALTER TABLE public.flights ADD CONSTRAINT flights_fk FOREIGN KEY (rocket_id) REFERENCES rockets(id);


-- Drop table

-- DROP TABLE public.links;

CREATE TABLE public.links (
	id int4 NOT NULL,
	flight_id int4 NOT NULL,
	mission_patch text NULL,
	mission_patch_small text NULL,
	article_link text NULL,
	CONSTRAINT links_pk PRIMARY KEY (id)
);

ALTER TABLE public.links ADD CONSTRAINT links_fk FOREIGN KEY (flight_id) REFERENCES flights(id);



-- Drop table

-- DROP TABLE public.rockets;

CREATE TABLE public.rockets (
	id int4 NOT NULL,
	rocket_name text NOT NULL,
	rocket_type text NULL,
	CONSTRAINT rockets_pk PRIMARY KEY (id)
);
